spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monte_carlo_premier_league
    username: postgres
    password: admin
  driver-class-name: org.postgresql.Driver

  jpa:
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
